export type H1Operation = {
  name: string;
  title: string;
  method: "GET"|"POST"|"PUT"|"PATCH"|"DELETE";
  path: string;
  multipart?: boolean;
};

// Current documented HackerOne v1 operation catalog.
// Fixed method/path per operation; no arbitrary-path public MCP tool is required.
export const H1_OPERATIONS: H1Operation[] = [
  ["customer_get_activity","Get Activity","GET","/activities/{id}"],
  ["customer_query_activities","Query Activities","GET","/incremental/activities"],
  ["customer_get_analytics_data","Get Analytics Data","GET","/analytics"],
  ["customer_get_credentials","Get Credentials","GET","/programs/{program_id}/credentials"],
  ["customer_create_credential","Create a Credential","POST","/programs/{program_id}/credentials"],
  ["customer_update_credential","Update a Credential","PATCH","/programs/{program_id}/credentials/{id}"],
  ["customer_assign_credential","Assign a Credential","POST","/programs/{program_id}/credentials/{id}/assign"],
  ["customer_delete_credential","Delete a Credential","DELETE","/programs/{program_id}/credentials/{id}"],
  ["customer_revoke_credential","Revoke a Credential","POST","/programs/{program_id}/credentials/{id}/revoke"],
  ["customer_get_credential_inquiry_responses","Get Credential Inquiry Responses","GET","/programs/{program_id}/credential_inquiries/{credential_inquiry_id}/credential_inquiry_responses"],
  ["customer_delete_credential_inquiry_response","Delete Credential Inquiry Response","DELETE","/programs/{program_id}/credential_inquiries/{credential_inquiry_id}/credential_inquiry_responses/{id}"],
  ["customer_create_credential_inquiry","Create a Credential Inquiry","POST","/programs/{program_id}/credential_inquiries"],
  ["customer_get_credential_inquiries","Get Credential Inquiries","GET","/programs/{program_id}/credential_inquiries"],
  ["customer_update_credential_inquiry","Update Credential Inquiry","PATCH","/programs/{program_id}/credential_inquiries/{id}"],
  ["customer_delete_credential_inquiry","Delete Credential Inquiry","DELETE","/programs/{program_id}/credential_inquiries/{id}"],
  ["customer_send_email","Send email","POST","/organizations/{organization_id}/emails"],
  ["customer_create_hai_completion","Create Completion (Preview)","POST","/hai/completions"],
  ["customer_get_hai_completions","Get Completions (Preview)","GET","/hai/completions"],
  ["customer_get_your_organizations","Get Your Organizations","GET","/me/organizations"],
  ["customer_get_organization_audit_log","Get Audit Log","GET","/organizations/{organization_id}/audit_log"],
  ["customer_get_all_eligibility_settings","Get All Eligibility Settings","GET","/organizations/{organization_id}/eligibility_settings"],
  ["customer_get_eligibility_setting","Get Eligibility Setting","GET","/organizations/{organization_id}/eligibility_settings/{id}"],
  ["customer_get_all_inboxes","Get All Inboxes","GET","/organizations/{organization_id}/inboxes"],
  ["customer_get_pending_invitations","Get Pending Invitations","GET","/organizations/{organization_id}/invitations"],
  ["customer_create_invitation","Create An Invitation","POST","/organizations/{organization_id}/invitations"],
  ["customer_get_group","Get Group","GET","/organizations/{organization_id}/groups/{id}"],
  ["customer_update_group","Update Group","PATCH","/organizations/{organization_id}/groups/{id}"],
  ["customer_get_all_groups","Get All Groups","GET","/organizations/{organization_id}/groups"],
  ["customer_create_group","Create Group","POST","/organizations/{organization_id}/groups"],
  ["customer_get_all_members","Get All Members","GET","/organizations/{organization_id}/members"],
  ["customer_get_member","Get Member","GET","/organizations/{organization_id}/members/{id}"],
  ["customer_remove_member","Remove Member","DELETE","/organizations/{organization_id}/members/{id}"],
  ["customer_update_member","Update Member","PATCH","/organizations/{organization_id}/members/{id}"],
  ["customer_get_all_organization_programs","Get All Programs","GET","/organizations/{organization_id}/programs"],

  ["customer_get_your_programs","Get Your Programs","GET","/me/programs"],
  ["customer_get_allowed_reporter_activities","Get Allowed Reporter Activities","GET","/programs/{id}/allowed_reporters/{username}/activities"],
  ["customer_get_allowed_reporter_username_history","Get Allowed Reporter username history","GET","/programs/{id}/allowed_reporters/{username}/history"],
  ["customer_get_allowed_reporters","Get Allowed Reporters","GET","/programs/{id}/allowed_reporters"],
  ["customer_get_allowed_reporters_history","Get Allowed Reporters History","GET","/programs/{id}/allowed_reporters/history"],
  ["customer_get_program_audit_log","Get Audit Log","GET","/programs/{id}/audit_log"],
  ["customer_get_program_balance","Get Your Programs Balance","GET","/programs/{id}/balance"],
  ["customer_get_payment_transactions","Get Payment Transactions","GET","/programs/{id}/transactions"],
  ["customer_award_program_bounty","Award Bounty","POST","/programs/{id}/bounties"],
  ["customer_get_bounty_table","Get Bounty Table","GET","/programs/{id}/bounty_table"],
  ["customer_get_all_campaigns","Get All Campaigns","GET","/programs/{id}/campaigns"],
  ["customer_create_campaign","Create Campaign","POST","/programs/{id}/campaigns"],
  ["customer_get_campaign","Get Campaign","GET","/programs/{id}/campaigns/{campaign_id}"],
  ["customer_update_campaign","Update Campaign","PATCH","/programs/{id}/campaigns/{campaign_id}"],
  ["customer_launch_campaign","Launch Campaign","POST","/programs/{id}/campaigns/{campaign_id}/launch"],
  ["customer_end_campaign","End Campaign Prematurely","POST","/programs/{id}/campaigns/{campaign_id}/end"],
  ["customer_get_common_responses","Get Common Responses","GET","/programs/{id}/common_responses"],
  ["customer_create_cve_request","Create a CVE Request","POST","/programs/{id}/cve_requests"],
  ["customer_get_all_cve_requests","Get all CVE Requests","GET","/programs/{id}/cve_requests"],
  ["customer_get_hacker_invitations","Get Hacker Invitations","GET","/programs/{id}/hacker_invitations"],
  ["customer_invite_hackers","Invite Hackers to Program","POST","/programs/{id}/hacker_invitations"],
  ["customer_get_program_members","Get Program Members","GET","/programs/{id}/members"],
  ["customer_notify_external_platform","Notify External Platform","POST","/programs/{id}/external_notifications"],
  ["customer_upload_policy_attachments","Upload Policy Attachments","POST","/programs/{id}/policy/attachments",true],
  ["customer_update_policy","Update Policy","PATCH","/programs/{id}/policy"],
  ["customer_get_reporters","Get Reporters","GET","/programs/{id}/reporters"],
  ["customer_get_scope_exclusions","Get Scope Exclusions","GET","/programs/{id}/scope_exclusions"],
  ["customer_create_scope_exclusion","Create Scope Exclusion","POST","/programs/{id}/scope_exclusions"],
  ["customer_update_scope_exclusion","Update Scope Exclusion","PATCH","/programs/{id}/scope_exclusions/{scope_exclusion_id}"],
  ["customer_delete_scope_exclusion","Delete Scope Exclusion","DELETE","/programs/{id}/scope_exclusions/{scope_exclusion_id}"],
  ["customer_get_structured_scopes","Get Structured Scopes","GET","/programs/{id}/structured_scopes"],
  ["customer_get_awarded_swag","Get Awarded Swag","GET","/programs/{id}/swag"],
  ["customer_mark_swag_sent","Mark Swag as Sent","PATCH","/programs/{id}/swag/{swag_id}"],
  ["customer_send_messages_to_hackers","Send Messages to Hackers","POST","/programs/{id}/messages"],
  ["customer_get_thanks","Get Thanks to Hackers","GET","/programs/{id}/thanks"],
  ["customer_get_integrations","Get Integrations","GET","/programs/{id}/integrations"],
  ["customer_get_triage_reviews","Get Triage Reviews","GET","/programs/{id}/triage_reviews"],
  ["customer_get_weaknesses","Get Weaknesses","GET","/programs/{id}/weaknesses"],
  ["customer_get_program","Get Program","GET","/programs/{id}"],

  ["customer_import_assets_csv","Import assets with CSV file","POST","/organizations/{organization_id}/assets/imports",true],
  ["customer_get_assets_import","Retrieve an assets import","GET","/organizations/{organization_id}/assets/imports/{id}"],
  ["customer_attach_asset_screenshot","Attach screenshot to asset","POST","/organizations/{organization_id}/assets/{asset_id}/screenshots",true],
  ["customer_get_asset_tag_categories","Get All Asset Tag Categories","GET","/organizations/{organization_id}/asset_tag_categories"],
  ["customer_create_asset_tag_category","Create Asset Tag Category","POST","/organizations/{organization_id}/asset_tag_categories"],
  ["customer_get_asset_tags","Get All Asset Tags","GET","/organizations/{organization_id}/asset_tags"],
  ["customer_create_asset_tag","Create Asset Tag","POST","/organizations/{organization_id}/asset_tags"],
  ["customer_list_asset_ports","List asset ports","GET","/organizations/{organization_id}/assets/{asset_id}/ports"],
  ["customer_create_asset_port","Create asset port","POST","/organizations/{organization_id}/assets/{asset_id}/ports"],
  ["customer_delete_asset_port","Delete asset port","DELETE","/organizations/{organization_id}/assets/{asset_id}/ports/{id}"],
  ["customer_get_asset_reachability","Get Asset Reachability Status","GET","/organizations/{organization_id}/assets/{asset_id}/reachability"],
  ["customer_check_asset_reachability","Check Asset Reachability","POST","/organizations/{organization_id}/assets/{asset_id}/reachability"],
  ["customer_get_asset_scanner_configuration","Get asset scanner configuration","GET","/organizations/{organization_id}/assets/{asset_id}/scanner_configuration"],
  ["customer_update_asset_scanner_configuration","Update asset scanner configuration","PUT","/organizations/{organization_id}/assets/{asset_id}/scanner_configuration"],
  ["customer_add_asset_to_scope","Add asset to scope","POST","/organizations/{organization_id}/assets/{asset_id}/scopes"],
  ["customer_update_asset_scope","Update asset scope","PATCH","/organizations/{organization_id}/assets/{asset_id}/scopes/{id}"],
  ["customer_archive_asset_scopes","Archive asset scopes","POST","/organizations/{organization_id}/asset_scopes/archive"],
  ["customer_get_asset","Get Asset","GET","/organizations/{organization_id}/assets/{id}"],
  ["customer_update_asset","Update Asset","PUT","/organizations/{organization_id}/assets/{id}"],
  ["customer_get_all_assets","Get All Assets","GET","/organizations/{organization_id}/assets"],
  ["customer_create_asset","Create Asset","POST","/organizations/{organization_id}/assets"],
  ["customer_archive_assets","Archive Assets","POST","/organizations/{organization_id}/assets/archive"],

  ["customer_get_all_automations","Get All Automations","GET","/organizations/{organization_id}/automations"],
  ["customer_create_automation","Create Automation","POST","/organizations/{organization_id}/automations"],
  ["customer_get_automation","Get Automation","GET","/organizations/{organization_id}/automations/{id}"],
  ["customer_update_automation","Update Automation","PATCH","/organizations/{organization_id}/automations/{id}"],
  ["customer_get_automation_runs","Get All Automation Runs","GET","/organizations/{organization_id}/automations/{id}/runs"],
  ["customer_trigger_automation","Trigger Automation","POST","/organizations/{organization_id}/automations/{id}/runs"],
  ["customer_get_automation_run","Get Automation Run","GET","/organizations/{organization_id}/automations/{automation_id}/runs/{id}"],
  ["customer_get_automation_run_logs","Get Automation Run Logs","GET","/organizations/{organization_id}/automations/{automation_id}/runs/{id}/logs"],

  ["customer_get_all_workboards","Get All Workboards","GET","/organizations/{organization_id}/findings/workboards"],
  ["customer_create_workboard","Create Workboard","POST","/organizations/{organization_id}/findings/workboards"],
  ["customer_get_workboard","Get Workboard","GET","/organizations/{organization_id}/findings/workboards/{id}"],
  ["customer_update_workboard","Update Workboard","PATCH","/organizations/{organization_id}/findings/workboards/{id}"],
  ["customer_delete_workboard","Delete Workboard","DELETE","/organizations/{organization_id}/findings/workboards/{id}"],
  ["customer_get_all_views","Get All Views","GET","/organizations/{organization_id}/findings/views"],
  ["customer_create_view","Create View","POST","/organizations/{organization_id}/findings/views"],
  ["customer_get_view","Get View","GET","/organizations/{organization_id}/findings/views/{id}"],
  ["customer_update_view","Update View","PATCH","/organizations/{organization_id}/findings/views/{id}"],
  ["customer_delete_view","Delete View","DELETE","/organizations/{organization_id}/findings/views/{id}"],
  ["customer_get_view_reports","Get View Reports","GET","/organizations/{organization_id}/findings/views/{id}/reports"],

  ["customer_create_report_comment","Create Comment","POST","/reports/{id}/activities"],
  ["customer_update_report_assignee","Update Assignee","POST","/reports/{id}/assignee"],
  ["customer_upload_report_attachments","Upload Attachments","POST","/reports/{id}/attachments",true],
  ["customer_delete_report_attachments","Delete Attachments","DELETE","/reports/{id}/attachments"],
  ["customer_award_report_bounty","Award Bounty","POST","/reports/{id}/bounties"],
  ["customer_mark_report_ineligible","Mark as Ineligible for Bounty","POST","/reports/{id}/bounties/ineligible"],
  ["customer_list_bounty_suggestions","List bounty suggestions","GET","/reports/{id}/bounty_suggestions"],
  ["customer_create_bounty_suggestion","Create bounty suggestion","POST","/reports/{id}/bounty_suggestions"],
  ["customer_close_comments","Close Comments","POST","/reports/{id}/close_comments"],
  ["customer_manage_custom_field_values","Manage Custom Field Values","POST","/reports/{id}/custom_field_values"],
  ["customer_update_cves","Update CVEs","POST","/reports/{id}/cves"],
  ["customer_update_disclosure_request","Update Disclosure Request","POST","/reports/{id}/disclosure_request"],
  ["customer_cancel_disclosure_request","Cancel Disclosure Request","DELETE","/reports/{id}/disclosure_request"],
  ["customer_update_inboxes","Update inboxes","POST","/reports/{id}/inboxes"],
  ["customer_add_participant","Add participant","POST","/reports/{id}/participants"],
  ["customer_generate_pdf","Generate PDF","POST","/reports/{id}/pdf"],
  ["customer_redact_report","Redact report","POST","/reports/{id}/redact"],
  ["customer_escalate_report","Escalate Report","POST","/reports/{id}/escalate"],
  ["customer_remove_escalation","Remove Escalation","DELETE","/reports/{id}/escalate"],
  ["customer_update_report_tags","Update Report Tags","POST","/reports/{id}/tags"],
  ["customer_request_retest","Request Retest","POST","/reports/{id}/retests"],
  ["customer_approve_retest","Approve Retest","POST","/reports/{id}/retests/approve"],
  ["customer_reject_retest","Reject Retest","POST","/reports/{id}/retests/reject"],
  ["customer_cancel_retest","Cancel Retest","POST","/reports/{id}/retests/cancel"],
  ["customer_update_severity","Update Severity","POST","/reports/{id}/severity"],
  ["customer_change_state","Change State","POST","/reports/{id}/state"],
  ["customer_update_structured_scope","Update Structured Scope","POST","/reports/{id}/structured_scope"],
  ["customer_add_summary","Add Summary","POST","/reports/{id}/summaries"],
  ["customer_award_swag","Award Swag","POST","/reports/{id}/swag"],
  ["customer_update_title","Update Title","POST","/reports/{id}/title"],
  ["customer_transfer_report","Transfer Report","POST","/reports/{id}/transfer"],
  ["customer_update_weakness","Update Weakness","POST","/reports/{id}/weakness"],
  ["customer_get_all_reports","Get All Reports","GET","/reports"],
  ["customer_create_report","Create Report","POST","/reports"],
  ["customer_get_report","Get Report","GET","/reports/{id}"],
  ["customer_update_reference","Update Reference","POST","/reports/{id}/reference"],
  ["customer_get_user","Get User","GET","/users/{username}"],
  ["customer_get_user_by_id","Get User By ID","GET","/users/id/{id}"],

  ["hacker_get_hacktivity","Get Hacktivity","GET","/hackers/hacktivity"],
  ["hacker_get_reports","Get Reports","GET","/hackers/me/reports"],
  ["hacker_create_report","Create Report","POST","/hackers/reports"],
  ["hacker_get_report","Get Report","GET","/hackers/reports/{id}"],
  ["hacker_get_balance","Get Balance","GET","/hackers/payments/balance"],
  ["hacker_get_earnings","Get Earnings","GET","/hackers/payments/earnings"],
  ["hacker_get_payouts","Get Payouts","GET","/hackers/payments/payouts"],
  ["hacker_get_programs","Get Programs","GET","/hackers/programs"],
  ["hacker_get_program","Get Program","GET","/hackers/programs/{handle}"],
  ["hacker_get_scope_exclusions","Get Scope Exclusions","GET","/hackers/programs/{handle}/scope_exclusions"],
  ["hacker_get_structured_scopes","Get Structured Scopes","GET","/hackers/programs/{handle}/structured_scopes"],
  ["hacker_get_weaknesses","Get Weaknesses","GET","/hackers/programs/{handle}/weaknesses"],
  ["hacker_get_report_intents","Get Report Intents","GET","/hackers/report_intents"],
  ["hacker_create_report_intent","Create Report Intent","POST","/hackers/report_intents"],
  ["hacker_get_report_intent","Get Report Intent","GET","/hackers/report_intents/{id}"],
  ["hacker_update_report_intent","Update Report Intent","PATCH","/hackers/report_intents/{id}"],
  ["hacker_delete_report_intent","Delete Report Intent","DELETE","/hackers/report_intents/{id}"],
  ["hacker_submit_report_intent","Submit Report Intent","POST","/hackers/report_intents/{id}/submit"],
  ["hacker_get_report_intent_attachments","Get Report Intent Attachments","GET","/hackers/report_intents/{report_intent_id}/attachments"],
  ["hacker_upload_report_intent_attachments","Upload Report Intent Attachments","POST","/hackers/report_intents/{report_intent_id}/attachments",true],
  ["hacker_delete_report_intent_attachment","Delete Report Intent Attachment","DELETE","/hackers/report_intents/{report_intent_id}/attachments/{id}"],
].map(([name,title,method,path,multipart]) => ({name,title,method,path,multipart: !!multipart})) as H1Operation[];
